stages:
  - build
  - test

variables:
  PROJECT_NAME: pmayors-project
  JAVA_OPTS: ${JAVA_OPTIONS}
  MY_SECRET: ${MY_SECRET}

# Build stage
build-job:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  only:
    - main
  script:
    - echo "Building the project ${PROJECT_NAME}-build..."
    - echo "Using JAVA_OPTS: ${JAVA_OPTS}"
    - echo "My secret is ${MY_SECRET}"
    - echo "The source of the pipeline trigger is $CI_PIPELINE_SOURCE for branch $CI_COMMIT_BRANCH"
    - mvn install

# Test stage
test-job:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  only:
    - main
  script:
    - echo "Running tests on ${PROJECT_NAME}-test..."
    - mvn test



  