stages:
  - build
  - test
  - security

variables:
  PROJECT_NAME: pmayors-project
  JAVA_OPTS: ${JAVA_OPTIONS}
  MY_SECRET: ${MY_SECRET}

# Build stage
build-job:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  rules:
    # Trigger build on main and develop branches 
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
    # Trigger on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
    # Trigger when started manually
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # Trigger on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # Otherwise, do not run
    - when: never
  script:
    - echo "Building the project ${PROJECT_NAME}-build..."
    - mvn install
  artifacts:
    paths:
      - target/*.war
    when: always

# Test stage
test-job:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  needs: 
    - job: build-job
      artifacts: true
  rules:
    # Trigger build on main and develop branches 
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
    # Trigger on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
    # Trigger when started manually
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # Trigger on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # Otherwise, do not run
    - when: never
  script:
    - echo "Running tests on ${PROJECT_NAME}-test..."
    - mvn test
  after_script:
    - ls -la
  artifacts:
    paths:
      - target/*.war
    when: always

security-scan-job:
  stage: security
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs: 
    - job: build-job
      artifacts: true
  script:
    - trivy fs --format json --exit-code 0 --vuln-type os, library --output trivy-results.json .
  after_script:
    - ls -la
  artifacts:
    paths:
      - trivy-results.json
    when: always




  