stages:
  - build
  - test
  - security
  - notify
  - docker

variables:
  PROJECT_NAME: pmayors-project
  JAVA_OPTS: ${JAVA_OPTIONS}
  MY_SECRET: ${MY_SECRET}

# Build stage
build-job:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  rules:
    # Trigger build on main and develop branches 
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
    # Trigger on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
    # Trigger when started manually
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # Trigger on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # Otherwise, do not run
    - when: never
  script:
    - echo "Building the project ${PROJECT_NAME}-build..."
    - mvn install
  artifacts:
    paths:
      - target/*.war
    when: always

# Test stage
test-job:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  needs: 
    - job: build-job
      artifacts: true
  rules:
    # Trigger build on main and develop branches 
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
    # Trigger on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
    # Trigger when started manually
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # Trigger on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # Otherwise, do not run
    - when: never
  script:
    - echo "Running tests on ${PROJECT_NAME}-test..."
    - mvn test
  after_script:
    - ls -la
  artifacts:
    paths:
      - target/*.war
    when: always

security-scan-job:
  stage: security
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs: 
    - job: build-job
      artifacts: true
  script:
    - trivy fs --debug --format json --exit-code 0 --vuln-type os,library --output trivy-results.json . || true
  after_script:
    - ls -la
  artifacts:
    paths:
      - trivy-results.json
    when: always

docker-build-publish:
  stage: docker 
  image: docker:latest
  services:
    - docker:dind
  needs: 
    - job: security-scan-job
      artifacts: true
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: $CI_COMMIT_SHA
  script:
    - echo "Logging in to GitLab Container Registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Building Docker image with custom dockerfile..."
    - docker build -f Docker-files/app/multistage/Dockerfile -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG



#--------------------------------
# Notify on Failure Job
#--------------------------------
notify-on-failure:
  stage: notify
  script:
    - echo "Build test failed, {PROJECT_NAME} Please check logs."
  when: on_failure


